version: '3.4'

services:
  myapp:
    image: tg-sticker-maker-bot:latest
    build:
      context: .
      dockerfile: TgStickerMakerBot/Dockerfile
    environment:
      - AppSettings__FFmpegPath=ffmpeg
      - AppSettings__BotSettings__BotToken=7497308682:AAGTrY7Za9NDQTZbUYW166iwQFAClYgyjCs
    ports:
      - "5144:8080"
