version: '3.4'

services:
  myapp:
    image: tg-sticker-maker-bot:latest
    build:
      context: .
      dockerfile: TgStickerMakerBot/Dockerfile
    environment:
      - APPSETTINGS__FFMPEGPATH=${FFmpegPath}
      - APPSETTINGS__SECRETSPATH=${SecretsPath}
    secrets:
     - bot_token
    env_file:
      - .env
    ports:
      - "5144:8080"
secrets:
  bot_token:
    file: ./bot_token.txt
