name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            cd TgStickerMakerBot/
            git pull origin main
            docker-compose build
            docker-compose up -d
        '
