name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        MY_SECRET: ${{ secrets.BOT_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            cd /path/to/your/app
            git pull origin main
            docker-compose build
            docker-compose up -d
        '
