name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      run: |
        docker-compose build

    - name: Deploy to server
      env:
        MY_SECRET: ${{ secrets.BOT_TOKEN }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            cd TgStickerMaker/
            docker-compose up -d
